---
#create master node
- hosts: tag_Name_aws_sandbox_tf_1 
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors all
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
    - name: create .kube directory
      become: yes
      become_user: k8suser
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755  
    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/k8suser/.kube/config
        remote_src: yes
        owner: k8suser
    - name: install Pod network
      become: yes
      become_user: k8suser
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
      args:
        chdir: $HOME
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: k8suser
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command
    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777