#create variables in local host
- hosts: localhost
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: gather hostvar
      lineinfile:
        line: "{{hostvars[tag_Name_aws_sandbox_tf_1].ansible_hostname}}:{{hostvars[tag_Name_aws_sandbox_tf_1].ansible_default_ipv4.address}}"
        path: ./tf_hosts.txt