#Ansible Jenkins Master, sample playbook - jenkins-master-sample.yml
---
- hosts: tag_Name_aws_sandbox_tf_1
  #hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes