#create variables in local host
- hosts: localhost
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: set permission
      file:
        path: ../setlocalvar.sh
        mode: u+x
    - name: Run a script with arguments (using 'cmd' parameter)
      command: 
        cmd: source ../setlocalvar.sh
        chdir: ~/tf_aws_k8s
